Adds subscription apis and validate version support
nutanix/kafka-rest-node pull request #1
Opened 2019-05-14 13:53 UTC by venkhatv

Adds subscription apis and validate version support

2019-05-16 09:10 UTC, ashvinikumars commented on lib/consumers.js
> +ConsumerInstance.prototype.getSubscriptionDetails = function(res) {
We could also do it like this,
```
ConsumerInstance.prototype.getSubscriptionDetails = function(res) {
    return new Promise((resolve, reject) => {
        this.client.request(utils.urlJoin(this.getUri(), 'subscription'), (err, result) => {
            if (res) {
                res(err, result);
            } else if (err) {
                reject(err);
            } else {
                resolve(result);
            }
        });
    });
}
```

2019-05-17 05:13 UTC, ashvinikumars commented on examples/console_consumer.v2.js
> +        url: "https://skiff-api.dev.saas.nutanix.com",
Use generic urls like http://example.com instead of company specific ones. Same for group and topic. test-group and test-topic.

2019-05-17 09:44 UTC, venkhatv commented
1. Added support for all new consumer apis
2. Added promise support, version check for v2 and v1 apis in consumers n brokers.

Things to do:
1.  Add Promise and version check in Topics, partitions.
2. Test throughly v1, v2 apis in All files, via callback and promise .
3.  Unit test cases
4. Clean up example files

2019-05-22 10:22 UTC, venkhatv commented
Cleaned up all files

Things to do:
Write unit test cases

2019-05-29 08:07 UTC, venkhatv commented
1. Added Unit test
2. Formatted lib files, examples, test files.

Pls check formatting, indendation, and code readability

2019-06-02 14:16 UTC, ashvinikumars requested changes
Overall it looks good. There are a couple of comments. Once you resolve them, we can merge this PR.

2019-06-02 14:16 UTC, ashvinikumars commented on examples/console_consumer.v2.js
> +    consumerConfig['auto.offset.reset'] = 'smallest';
This won't work. Valid values are earliest, latest and none. The value influences the initial offset when there is no saved offset for the consumer group. This would happen when the consumer group is connecting for the first time or when the saved offset is out of range. If the user specifies a consumer group name and wants to re-run the example a second time, consuming messages from beginning this will not work. There are APIs available to move the offset to beginning before starting to consume messages. These APIs need to be used. 
To keep the example simple, either remove the option to specify consumer group name so that we always create a new consumer group or remove the fromBeginning.

2019-06-02 14:16 UTC, ashvinikumars commented on examples/console_consumer.v2.js
> +var subscriptionsTopics = {
Rename variable to subscribedTopics

2019-06-02 14:16 UTC, ashvinikumars commented on lib/client.js
> +//Use this, when body is sent in Get request
Which REST proxy API requires/ allows a body in GET method?

2019-06-02 14:16 UTC, ashvinikumars commented on examples/console_consumer.v2.js
> +    console.log("Usage: node console_consumer.js [--url <api-base-url>] --topic <topic> [--group <consumer-group-name>] [--message-limit <num_messages>] [--from-beginning] [--format <avro|binary>]");
Limit line length to 120 to avoid need of horizontal scrolling when viewing in Github

2019-06-03 09:09 UTC, ashvinikumars commented on lib/client.js
> +//Use this, when body is sent in Get request
Just noticed that the Get committed offsets API accepts a request body.

2019-06-11 08:50 UTC, merged